language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

before_install:
  - apt-get update && apt-get install findutils
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - bin/phulp test

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
